# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Heracles' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Heracles
pod 'FBSDKCoreKit', '~> 4.10.0'
pod 'FBSDKLoginKit', '~> 4.10.0'
pod 'FBSDKShareKit', '~> 4.10.0'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'ScrollableGraphView'
pod "Gradients"
end
